-- KULLANICI_FEEDBACK tablosu: Kullanıcı geri bildirimlerini saklama
use TESTDB;
GO
IF OBJECT_ID('dbo.KULLANICI_FEEDBACK', 'U') IS NOT NULL
    DROP TABLE dbo.KULLANICI_FEEDBACK;
GO

CREATE TABLE dbo.KULLANICI_FEEDBACK (
    Id INT PRIMARY KEY IDENTITY(1,1),
    TcKimlikNo NVARCHAR(50) NOT NULL,
    MesajOzet NVARCHAR(500) NULL,
    Reaksiyon NVARCHAR(20) NOT NULL, -- 'positive', 'negative'
    FeedbackTarihi DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE INDEX IX_KULLANICI_FEEDBACK_TcKimlikNo ON dbo.KULLANICI_FEEDBACK(TcKimlikNo);
CREATE INDEX IX_KULLANICI_FEEDBACK_Tarih ON dbo.KULLANICI_FEEDBACK(FeedbackTarihi);
GO
